# Generated by Django 5.0.1 on 2024-01-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام و نام خانوادگی')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال/غیرفعال')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره موبایل')),
                ('password', models.CharField(max_length=15, verbose_name='کلمه عبور')),
            ],
            options={
                'verbose_name': 'مدیریت مشتری',
                'verbose_name_plural': 'مدیریت مشتریان',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('customerUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApp.customeruser')),
            ],
            options={
                'verbose_name': 'مدیریت آدرس',
                'verbose_name_plural': 'مدیریت آدرس ها',
            },
        ),
    ]
